In [1]:
import numpy as np
import pandas as pd

### Import Dataset

In [2]:
## Construct a dataframe from the csv dataset
colnames=['year', 'month', 'day', 'RMM1', 'RMM2','phase','amplitude','Final_value']
df = pd.read_csv('../data/obs/rmm.74toRealtime.txt', sep=r'[ \t]+', names=colnames, skiprows=[0])
total_days = len(df)

## Convert the columns of the dataframe to the numpy array
year = df['year'].to_numpy()
month = df['month'].to_numpy()
day = df['day'].to_numpy()

RMM1 = df['RMM1'].to_numpy(dtype='float64')
RMM2 = df['RMM2'].to_numpy(dtype='float64')
phase = df['phase'].to_numpy(dtype='float64')
amplitude = df['amplitude'].to_numpy(dtype='float64')

print(df)

       year  month  day      RMM1      RMM2  phase  amplitude  \
0      1974      6    1  1.634470  1.203040      5   2.029480   
1      1974      6    2  1.602890  1.015120      5   1.897290   
2      1974      6    3  1.516250  1.085510      5   1.864760   
3      1974      6    4  1.509810  1.035730      5   1.830920   
4      1974      6    5  1.559060  1.305180      5   2.033260   
...     ...    ...  ...       ...       ...    ...        ...   
18294  2024      7    2  0.386045 -1.403167      3   1.455303   
18295  2024      7    3  0.367469 -1.546910      3   1.589958   
18296  2024      7    4  0.209546 -1.451836      3   1.466880   
18297  2024      7    5  0.202304 -1.161427      3   1.178915   
18298  2024      7    6  0.412928 -1.050201      3   1.128464   

                                  Final_value  
0                WH04_method:_OLR_&_NCEP_wind  
1                WH04_method:_OLR_&_NCEP_wind  
2                WH04_method:_OLR_&_NCEP_wind  
3                WH04_metho

/var/folders/51/_9h2_qzn4b54cgs0qgwxr0vh0000gn/T/ipykernel_65876/2826871129.py:3: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df = pd.read_csv('../data/obs/rmm.74toRealtime.txt', sep=r'[ \t]+', names=colnames, skiprows=[0])


### Delete missing values and their preceding values

In [3]:
raw_datas = [RMM1,RMM2,phase,amplitude]
data_names = ['RMM1', 'RMM2', 'phase', 'amplitude']
idx_miss = np.where(RMM1 > 1e34)[0] # index of missing value
n_miss = len(idx_miss) # the number of missing value

## Delete the missing values and their predceding values
new_datas = [0]*4
for i in range(4):
    raw_data = raw_datas[i]
    data_name = data_names[i]
    dat = np.delete(raw_data, np.arange(max(idx_miss)+1)) # np.delete(raw_datas[i], idx_miss)
    new_datas[i] = dat
    if i == 0:
        RMM1_new = dat
    if i == 1:
        RMM2_new = dat
    if i == 2:
        phase_new = dat
    if i == 3:
        amplitude_new = dat

raw_ymds = [year, month, day]
ymd_names = ['year', 'month', 'day']
new_ymds = [0]*3
for i in range(3):
    raw_ymd = raw_ymds[i]
    tmd_name = ymd_names[i]
    dat_ymd = np.delete(raw_ymd, np.arange(max(idx_miss)+1)) # np.delete(raw_ymds[i], idx_miss)
    new_ymds[i] = dat_ymd
    if i == 0:
        year_new = dat_ymd
    if i == 1:
        month_new = dat_ymd
    if i == 2:
        day_new = dat_ymd
    

print(new_datas)
print(RMM1.shape)
print(max(idx_miss)+1)
print(RMM1_new.shape)

print(new_ymds)
print(year.shape)
print(year_new.shape)

[array([ 0.142507  , -0.2042    , -0.15861   , ...,  0.20954639,
        0.20230356,  0.4129284 ]), array([ 1.05047  ,  1.37361  ,  1.53943  , ..., -1.4518361, -1.1614273,
       -1.0502005]), array([6., 7., 7., ..., 3., 3., 3.]), array([1.0600899, 1.3887   , 1.54758  , ..., 1.4668803, 1.1789148,
       1.1284639])]
(18299,)
1675
(16624,)
[array([1979, 1979, 1979, ..., 2024, 2024, 2024]), array([1, 1, 1, ..., 7, 7, 7]), array([1, 2, 3, ..., 4, 5, 6])]
(18299,)
(16624,)


### Save and load the updated dataset

In [4]:
kwds = {'year':year_new, 'month':month_new, 'day':day_new, 'RMM1':RMM1_new, 'RMM2':RMM2_new,'phase':phase_new,'amplitude':amplitude_new}
np.savez('../data/obs/mjo_new_data.npz', **kwds)

npzfile = np.load('../data/obs/mjo_new_data.npz', allow_pickle=True)
print(npzfile.files)
print(npzfile['RMM1'])
print(npzfile['RMM2'])
print(npzfile['year'])
print(npzfile['month'])
print(npzfile['day'])

['year', 'month', 'day', 'RMM1', 'RMM2', 'phase', 'amplitude']
[ 0.142507   -0.2042     -0.15861    ...  0.20954639  0.20230356
  0.4129284 ]
[ 1.05047    1.37361    1.53943   ... -1.4518361 -1.1614273 -1.0502005]
[1979 1979 1979 ... 2024 2024 2024]
[1 1 1 ... 7 7 7]
[1 2 3 ... 4 5 6]
